### ISSUE TITLE
early results

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/well_duplicates#1]
I ran it on a bunch of run and it crashed in almost all of them on lane 8.
I'm still looking into why this happens and will open a separate issue for it.
I did however compare the results it gave for the first 7 lanes to the duplicate rate I calculated (note that this is total duplicate rate PCR+optical) 
The results looks good overall but there seems to be some discrepancy/variation

![estimated_vs_real_dup_rate](https://cloud.githubusercontent.com/assets/650891/14813570/3843ec5a-0b9a-11e6-9524-5eaa68781e43.png)
X is duplicate rate calculated by samblaster (after alignment) Y is the estimated dup rate calculated by  well duplicate per lane at level 3.
Did you find the same results?

**Comment by JudithR** [comment]
Hi Tim, 

Yes, we see a similar 'overestimation' at high duplicate rates, don't have enough data for the low duplicate rate ones.

Judith

**Comment by tcezard** [comment]
I've updated my source and ran the same dataset. It's not completely finished yet but it looks good already.
There are still some underestimation but it is more consistent across the board. I'm using AccO at level 3
![estimate_vs_duplicate](https://cloud.githubusercontent.com/assets/650891/15017899/63b6f744-120f-11e6-9d32-ece68ff16742.png)
