### ISSUE TITLE
ZeroDivisionError on lane 8

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/well_duplicates#2]
I have run well duplicate on multiple runs with the same coord file and they all seems to fail on lane 8 with a zerodivisionError

``` python
Traceback (most recent call last):
  File "/home/U008/tcezard/Applications/optical_duplicates/count_optical_duplicates.py", line 188, in <module>
    main()
  File "/home/U008/tcezard/Applications/optical_duplicates/count_optical_duplicates.py", line 131, in main
    output_writer(lane, tile_dupl, args.level)
  File "/home/U008/tcezard/Applications/optical_duplicates/count_optical_duplicates.py", line 42, in output_writer
    perc_dup = t_tally / t_length * 100
ZeroDivisionError: division by zero
```

It print to screen the content of the tile_dupl  and I pasted bellow one of the tile

```
{'1101': [{'length': 0, 'tally': 0},
          {'length': 1950, 'tally': 56},
          {'length': 1950, 'tally': 30},
          {'length': 1950, 'tally': 29}],
```

Do you think it is a error in the coord file that cause this issue or something else entirely?

**Comment by JudithR** [comment]
Hi Tim, 
Your error is probably the result of a dud tile on lane 8, resulting in 0 targets being retrievable.
Apart from that, during the investigation we found a whole load of things wrong with how the values are calculated. So I appologise for the crappy code, it's kind of stuck in two minds. The percentages per level are correct, the cumulative percentages are best ignored. We are working on fixing it.
Judith

**Comment by tcezard** [comment]
Thank you Judith
I'll run again with a different coordinate file and see what I get

**Comment by tcezard** [comment]
I think I misidentified the problem here.
There are some of my run that failed with the error I showed in the description however it's only a few and is probably due to bad tile as you said.
However it seems that lane 8 is never processed and I think this is due to range(1,8)(https://github.com/EdinburghGenomics/well_duplicates/blob/master/count_well_duplicates.py#L70) which create a list that does not contain lane 8

``` python
range(1,8)
[1, 2, 3, 4, 5, 6, 7]
```

Happy to create a PR to fix this

**Comment by tbooth** [comment]
Hi Tim,
Funny - when looking at the code a couple of days ago I spotted the similar off-by-one bug on line 90 but completely missed this one.
I see you pushed a new version of count_well_duplicates.py to the repo.  We have various uncommitted edits at our end so I'll probably have to manually fold everything in, but my first job is to get test coverage on the output_writer function so that the behaviour of that code is well-specified.

**Comment by tcezard** [comment]
oops, I've already open a PR #3 .
just push whatever changes you need then I'll fix my branch and potentially  deleted it if nothing is left to change.

**Comment by tbooth** [comment]
There's a fundamental issue with how cumulative totals are calculated - fundamental as in we'll need to restructure the tile_dupl object to get the correct results.  So any local tweaks you add are likely to get swamped by that change.
Test coverage, as ever, is the answer!  All PRs with new unit test cases gratefully received!

**Comment by tcezard** [comment]
Alright I'll close the PR then.
Let me know when you have something for me to test

**Comment by tcezard** [comment]
That's now fixed
